server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
spring:
  # 使用shardingsphere 分库分表
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: slave
        password: password
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: slave
        password: password
      ds2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: slave
        password: password
    props:
      sql:
        show: true  #打印sql
    # 水平拆分的数据库（表） 配置分库 + 分表策略 行表达式分片策略
    # 分库策略
    sharding:
      tables:
        user:
          actualDataNodes: ds$->{0..2}.user_$->{0..1}
          databaseStrategy:
            inline:
              shardingColumn: id
          tableStrategy:
            inline:
              shardingColumn: id
          key-generator-column-name: id
  rabbitmq:
    port: 5672
    host: 192.168.4.18
    password: sasa
    username: sasa
  # 404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  # 404交给异常处理器处理
  resources:
    add-mappings: false
  redis:
    #redis中心=127.0.0.1
      host: 127.0.0.1
    #redis.host=10.75.202.11
      port: 6379
    #redis.password=123456
      maxTotal: 200
      maxIdle: 100
      minIdle: 8
      maxWaitMillis: 100000
      maxActive: 300
      testOnBorrow: true
      testOnReturn: true
    #Idle时进行连接扫描
      testWhileIdle: true
    #表示idle object evitor两次扫描之间要sleep的毫秒数
      timeBetweenEvictionRunsMillis: 30000
    #表示idle object evitor每次扫描的最多的对象数
      numTestsPerEvictionRun: 10
    #表示一个对象至少停留在idle状态的最短时间，然后才能被idle object evitor扫描并驱逐；这一项只有在timeBetweenEvictionRunsMillis大于0时才有意义
      minEvictableIdleTimeMillis: 60000
      timeout: 100000
  main:
    allow-bean-definition-overriding: true
mybatis:
  # Mybatis配置Mapper路径
  mapper-locations: classpath:mapper/*.xml
  # Mybatis配置Model类对应
  type-aliases-package: com.wang.model.entity

pagehelper:
  params: count=countSql
  # 指定分页插件使用哪种方言
  helper-dialect: mysql
  # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
  reasonable: 'true'
  support-methods-arguments: 'true'

mapper:
  # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
  not-empty: true

logging:
  # Debug打印SQL
  level.com.wang.mapper: debug


